# Generated by Django 3.0.4 on 2020-03-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_username', models.CharField(max_length=50, unique=True)),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_balance', models.IntegerField(default=0)),
                ('branch_password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeadBranch',
            fields=[
                ('hbranch_id', models.AutoField(primary_key=True, serialize=False)),
                ('hbranch_username', models.CharField(max_length=50, unique=True)),
                ('hbranch_balance', models.IntegerField(default=0)),
                ('hbranch_password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_username', models.CharField(max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=50)),
                ('account_mobile', models.CharField(max_length=10)),
                ('account_balance', models.IntegerField(default=0)),
                ('account_password', models.CharField(default='', max_length=100)),
                ('account_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headbranch.Branch')),
            ],
        ),
    ]
