# Generated by Django 3.0.4 on 2020-03-20 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headbranch', '0002_headbranch_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Transaction',
            fields=[
                ('branch_tra_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_tra_with', models.CharField(max_length=10)),
                ('branch_tra_account', models.IntegerField()),
                ('branch_tra_type', models.IntegerField()),
                ('branch_tra_amount', models.IntegerField()),
                ('branch_tra_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='headbranch_transaction',
            name='hbranch_tra_branch',
        ),
    ]
