# Generated by Django 3.0.4 on 2020-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headbranch', '0003_auto_20200320_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='headbranch_transaction',
            name='hbranch_tra_branch',
            field=models.IntegerField(default=0),
        ),
    ]
