# Generated by Django 3.0.4 on 2020-03-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headbranch', '0004_headbranch_transaction_hbranch_tra_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_transaction',
            name='branch_tra_branch',
            field=models.IntegerField(default=0),
        ),
    ]
